core/urls.py
"""
Define URL patterns for the Core application.

This module specifies the URL configurations for the Core app, mapping
routes to their corresponding view functions.
"""
from django.urls import path
from .views import home, about
# url patterns for core features
urlpatterns = [
    path("", home, name="home"),
    path("home/", home, name="home"),
    path("about/", about, name="about"),
]

profiles/urls.py
"""
Define URL patterns for user account and profile management.

This module specifies the URL configurations for managing user profiles
and account-related actions (login, signup, password reset, logout) in
the application. It includes paths for viewing, editing, and deleting
profiles, as well as handling authentication through Django Allauth.
"""
from django.urls import path, include
from allauth.account.views import LoginView, SignupView, PasswordResetView
from . import views

urlpatterns = [
    # Profile URL patterns
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<str:username>/delete_profile/', views.delete_account, name='delete_account'),
    # Account URL patterns
    path('accounts/login/', LoginView.as_view(template_name="allauth/account/login.html"), name="account_login"),
    # Signup
    path('accounts/signup/', SignupView.as_view(template_name="allauth/account/signup.html"), name="account_signup"),
    # Password Reset
    path('accounts/password/reset/', PasswordResetView.as_view(template_name="allauth/account/password_reset.html"), name="account_reset_password"),
    # logout
    path("logout/", views.logout, name="logout"),
    # Include allauth URLs
    path('accounts/', include('allauth.urls')),  
]

travel_buddy/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

# Custom error views
handler403 = views.custom_403_view

urlpatterns = [
    # Admin page
    path('admin/', admin.site.urls),
    
    # other apps
    path("", include("recommendations.urls")),
    path("", include("profiles.urls")),
    path("", include("core.urls")),
    
    # Summernote for rich text editing
    path('summernote/', include('django_summernote.urls')),
]

profiles/models.py
"""
Define the Profile model for user information storage.

This module contains the Profile model, which extends user functionality
by storing additional information such as bio, location, and avatar.
The avatar is managed using Cloudinary for image storage.
"""
from django.contrib.auth.models import User
from django.db import models
from cloudinary.models import CloudinaryField


class Profile(models.Model):
    """
    Represents a user's profile containing personal information and avatar.

    Args:
        user (OneToOneField): A relationship field linking profile to a User.
        bio (str): A short biography or description of the user.
        location (str): The user's location.
        avatar (CloudinaryField): An avatar image uploaded to Cloudinary.

    Description:
        Used to store user profile information, including the user's
        bio, location, and avatar. Links to the `User` model with a one-to-one
        relationship. The `avatar` field uses Cloudinary for image storage.
    """

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile'
        )
    bio = models.TextField(blank=True)
    location = models.CharField(max_length=100, blank=True)
    avatar = CloudinaryField(
        'image',
        default='avatars/default_avatar.png'
        )

    def __str__(self):
        """
        Return a string representation of the user's profile.

        Returns:
            str: The username followed by "'s Profile".
        """
        return f"{self.user.username}'s Profile"

profiles/forms.py
"""
Define the ProfileForm for user profile editing.

This module contains the ProfileForm class, which allows users to edit
their profile details, including bio, location, and avatar, with built-in
validation constraints.
"""
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    """
    Form to handle profile editing.

    Args:
        forms (django.forms.ModelForm):
        A base class for creating model-based forms.

    Description:
        This form is used to edit a user's profile, allowing them to update
        their bio, location, and avatar. Constraints are added for validation.
    """

    class Meta:
        """
        Metadata for the ProfileForm class.

        Specifies the model to be used (Profile) and the fields that
        should be included in the form (bio, location, avatar).
        """

        model = Profile
        fields = ['bio', 'location', 'avatar']

    def __init__(self, *args, **kwargs):
        """
        Initialize the form and update the avatar field to accept image files.

        Args:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        super().__init__(*args, **kwargs)
        self.fields['avatar'].widget.attrs.update({'accept': 'image/*'})

    def clean_bio(self):
        """
        Validate the bio field to ensure it's not too long.

        Max length constraint is set to 500 characters.

        Returns:
            str: The cleaned bio.

        Raises:
            ValidationError: If the bio exceeds 500 characters.
        """
        bio = self.cleaned_data.get('bio')
        if len(bio) > 500:
            raise forms.ValidationError("Bio cannot exceed 500 characters.")
        return bio

    def clean_avatar(self):
        """
        Validate the avatar field to ensure it has a valid file type.

        Args:
            avatar: The uploaded avatar image.

        Returns:
            avatar: The cleaned avatar image.

        Raises:
            ValidationError: If the avatar file type is invalid.
        """
        avatar = self.cleaned_data.get('avatar')
        allowed_extensions = ['.jpg', '.jpeg', '.png']
        avatar = self.cleaned_data.get("avatar")
        if avatar:
            extension = None  # Default to None

            if hasattr(avatar, "public_id") and "." in avatar.public_id:
                extension = avatar.public_id.split(".")[-1].lower()
            elif hasattr(avatar, "url") and "." in avatar.url:
                extension = avatar.url.split("?")[0].split(".")[-1].lower()

            if extension and f".{extension}" not in allowed_extensions:
                raise forms.ValidationError(
                    "Invalid file type. Allowed types: .jpg, .jpeg, .png."
                )
        return avatar

profiles/views.py
"""
Define views for user account and profile management.

This module handles views for displaying and editing user profiles,
deleting user accounts, and logging out users. It includes profile-related
actions such as viewing recommendations, updating profile information,
and handling account deletion with confirmation.
"""
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import logout as auth_logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from recommendations.models import Recommendation
from .import forms

# PROFILE VIEWS #


def profile(request, username):
    """
    Profile view to display user profile along with their recommendations.

    Args:
        request (HttpRequest): The request object to handle the request.
        username (str): The username of the user whose profile is being viewed.

    Returns:
        HttpResponse: Render profile page with the user's details
    """
    user = get_object_or_404(User.objects.select_related('profile'), username=username)
    recommendations = Recommendation.objects.filter(user=user)
    delete_account_url = reverse("delete_account", kwargs={"username": username})
    return render(request, "profiles/profile.html", {
        "profile": user.profile,
        "recommendations": recommendations,
        "can_edit": request.user == user,
        "delete_account_url": delete_account_url,
    })


@login_required
def edit_profile(request, username=None):
    """
    Edit profile view allowing users to update their profile information.

    Args:
        request (HttpRequest): The request object to handle the edit profile request.
        username (str, optional): The username of the profile to edit. Defaults to None.

    Returns:
        HttpResponse: Renders the edit profile page with the profile form.
    """
    if username and request.user.username != username:
        return render(request, "error/403.html", status=403)

    profile = get_object_or_404(User, username=username or request.user.username).profile

    if request.method == "POST":
        form = forms.ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect("profile", username=request.user.username)
        else:
            messages.error(request, "There were some issues with your submission. Please check the form.")
    else:
        form = forms.ProfileForm(instance=profile)
    return render(request, "profiles/edit_profile.html", {"form": form, "profile": profile})


@login_required
def delete_account(request, username=None):
    """
    View to delete a user's account after confirmation.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: Redirects and logs the user out after account deletion.
    """
    if username and request.user.username != username:
        return render(request, "error/403.html", status=403)

    if request.method == "POST":
        password = request.POST.get('password')

        user = authenticate(username=request.user.username, password=password)
        if user is not None:           
            user.profile.delete()
            user.delete()
            messages.success(request, "Your account has been deleted successfully.")
            logout(request)
            return redirect('home')
        else:
            messages.error(request, "Incorrect password. Please try again.")
            return redirect('profile', username=request.user.username)

    return redirect('profile', username=request.user.username)


# ALL AUTH ACCOUNT MANAGEMENT VIEWS #

def logout(request):
    """
    Logout view to log out the current user and redirect to recommendations.

    Args:
        request (HttpRequest): The request object for logging out the user.

    Returns:
        HttpResponse: Redirects the user to the recommendations page after logout.
    """
    auth_logout(request)
    return redirect('home')

profiles/templates/profiles/delete_profile.html
<!-- 

this isn't used we just need something for our url 
to point to as we need a url pattern otherwise we throw an error
we handle account deletion in the profile.html file with a modal 
and confirmation we will never display this page to the user.

-->

profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}

{% block content %}
    <div class="profile-edit-container container">
        <div class="form-wrapper row">
            <h1>Edit Profile</h1>
            
            <form method="POST" enctype="multipart/form-data" class="col-12">
                {% csrf_token %}
                
                <div class="row">
                    <!-- Avatar field (300px wide) -->
                    <div class="col-md-3 avatar-container">
                        <div class="form-group">
                            <label for="id_avatar">Avatar:</label>
                            <div class="avatar-image">
                                {% if user.profile.avatar %}
                                    <img id="avatar-img" src="{{ user.profile.avatar.url }}" alt="Avatar" class="avatar-img" onclick="document.getElementById('id_avatar').click();" />
                                {% else %}
                                    <img id="avatar-img" src="/path/to/default-avatar.jpg" alt="Default Avatar" class="avatar-img" onclick="document.getElementById('id_avatar').click();" />
                                {% endif %}
                            </div>
                            <input type="file" id="id_avatar" name="avatar" style="display: none;" accept=".jpg, .jpeg, .png" onchange="previewAvatar(event)">
                        </div>
                    </div>

                    <!-- Bio and Location fields -->
                    <div class="col-md-9 bio-container">
                        <div class="form-group">
                            <label for="id_bio">Bio:</label>
                            {{ form.bio }}
                        </div>

                        <div class="form-group">
                            <label for="id_location">Location:</label>
                            {{ form.location }}
                        </div>
                    </div>
                </div>

                <div class="form-actions">
                    <button type="submit" class="btn btn-primary">
                        Save Changes
                    </button>
                </div>

                {% if form.errors %}
                    <div class="alert alert-danger">
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li> 
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-4 col-lg-12">
    <!-- Username -->
    <h2 class="text-white text-center profile-name text-uppercase">{{ profile.user.username }}</h2>
    
    <!-- Profile Info -->
    <div class="row my-4">
        <div class="col-lg-4 col-md-6 text-center profile-avatar-container">
            {% if profile.avatar %}
                <img src="{{ profile.avatar.url }}" alt="{{ profile.user.username }}'s avatar" class="img-fluid profile-avatar">
            {% else %}
                <img src="{% static 'images/default_avatar.png' %}" alt="Default avatar" class="img-fluid profile-avatar">
            {% endif %}
        </div>
        <div class="col-lg-8 col-md-6 text-white bio">
            <p><strong class="details-header">Location:</strong> {{ profile.location }}</p>
            <p><strong class="details-header">Bio:</strong> {{ profile.bio }}</p>
        </div>
    </div>
    {% if user.is_authenticated and user == profile.user %}
    <div class="profile-buttons" style="height:45px">
        <a href="{% url 'edit_profile' username=request.user.username %}" class="btn btn-primary profile-edit-button">Edit Profile</a>
        <a href="{% url 'delete_account' username=request.user.username %}" class="btn btn-danger profile-delete-button" data-bs-toggle="modal" data-bs-target="#deleteAccountModal">Delete Account</a>
    </div>
    {% else %}
    <div style="height:45px">
        
    </div>
    {% endif %}
</div>
<!-- Recommendations -->
<div class="container mt-4 col-lg-12">
    <h3 class="mt-4 text-white">Recommendations</h3>
    <div class="accordion" id="recommendationAccordion">
        {% for recommendation in recommendations %}
        <div class="accordion-item">
                <h2 class="accordion-header" id="heading{{ recommendation.id }}">
                    <button class="accordion-button collapsed d-flex" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ recommendation.id }}" aria-expanded="false" aria-controls="collapse{{ recommendation.id }}">
                        <span>{{ recommendation.title }}</span>
                    </button>
                </h2>
            <div id="collapse{{ recommendation.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ recommendation.id }}" data-bs-parent="#recommendationAccordion">
                <div class="accordion-body text-white">
                    <div>
                        <strong class="accordion-title">Location:</strong>
                        <p>{{ recommendation.address }}</p>
                    </div>
                    <div>
                        <strong class="accordion-title">Description:</strong>
                        <p>{{ recommendation.description }}</p>
                    </div>
                    <div>
                        <strong class="accordion-title">Categories:</strong>
                        <p>{{ recommendation.category }}</p>
                    </div>
                    {% if user == profile.user %}
                    <div class="recommendation-buttons d-flex mt-3">
                        <div class="edit-button">
                            <a href="{% url 'edit_recommendation' recommendation_id=recommendation.id %}" class="btn btn-primary">Edit Recommendation</a>
                        </div>
                        <div class="delete-button">
                            <a href="{% url 'delete_recommendation' recommendation_id=recommendation.id %}" class="btn btn-danger btn-sm">Delete</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<!-- Account Deletion Confirmation Modal -->
{% include "modals/modal.html" with modal_id="deleteAccountModal" title="Confirm Account Deletion" message="This action is irreversible. Please confirm." context_type="account_deletion" action_url=delete_account_url submit_class="btn-danger" submit_label="Delete Account" %}

{% endblock %}